/**
 * Chat session and message types for persistent AI coach conversations
 */

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  createdAt: Date;
  planUpdated?: boolean;
}

export interface ChatSession {
  id: string;
  userId: string;
  title: string;
  createdAt: Date;
  updatedAt: Date;
  messageCount: number;
  lastMessage: string; // Truncated preview (~100 chars)
  isActive: boolean;
}

// For creating new messages (id and createdAt auto-generated by Firestore)
export type NewChatMessage = Omit<ChatMessage, 'id' | 'createdAt'>;

// For creating new sessions (most fields auto-generated)
export type NewChatSession = Pick<ChatSession, 'title'>;
